# serverless.yml
service: hello-service
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
